# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04e60f223ba5b232a09377798aebea2bf1b614a4bfc1332a3725e58031b7b6f9d442ebc9be5d67579e8f92062756b539f73b5e1a9d56a1df078b72d780a45846

test:
  secret_key_base: 2d5a6356827ea713ba35803d9cbff49a6eeb92a1dd8b9556f11c1de9f6c5a645d4d2df1c541722d0a3161941d5b37fb579393289352108a53e14074ac1ff9bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
